name: Build Go App
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_go:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    
    - name: Build Go
      run: go build -v ./...