name: Delete Failure Workflow Runs
on:
  workflow_dispatch:
    inputs:
      workflowActor: 
        description: "Who runs this workflow"
        required: false
        default: "sonadztux"
  # temp
  push:
    branches: [ master ]

jobs:
  delete_failure_runs:
    runs-on: ubuntu-latest

    steps:
      - name: List Failure Runs
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.SONADZTUX_GITHUB_ACTIONS_PAT }}
          run: |
            console.log(`Workflow Actor: ${{github.event.inputs.workflowActor}}`)
            const runs = await github.rest.actions.listWorkflowRunsForRepo({
              owner: 'sonadztux',
              repo: 'github-actions-testing',
              status: 'failure'
            })
      
      - name: Delete Failure Runs
        run: console.log(runs.data.workflow_runs)
