name: Delete Workflow Runs
on:
  workflow_dispatch:
    inputs:
      workflowId: 
        description: "Workflow ID"
        required: true

jobs:
  delete_runs:
    runs-on: ubuntu-latest

    steps:
      - name: List Runs In Workflow ID ${{github.event.inputs.workflowId}}
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.SONADZTUX_GITHUB_ACTIONS_PAT }}
          script: |
            const listWorkflowRuns = await github.rest.actions.listWorkflowRuns({
              owner: 'sonadztux',
              repo: 'github-actions-testing',
              workflow_id: ${{github.event.inputs.workflowId}},
              page: 1,
              per_page: 100
            })
            console.log(listWorkflowRuns)

