name: Delete Failure Workflow Runs
on:
  workflow_dispatch:
    inputs:
      workflowActor: 
        description: "Who runs this workflow"
        required: true
        default: "sonadztux"
  # temp
  push:
    branches: [ master ]

jobs:
  delete_failure_runs:
    runs-on: ubuntu-latest

    steps:
      - name: List Failure Runs
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.SONADZTUX_GITHUB_ACTIONS_PAT }}
          script: |
            console.log(`Workflow Actor: ${{github.event.inputs.workflowActor}}`)
            const runs = await github.rest.actions.listWorkflowRunsForRepo({
              owner: 'sonadztux',
              repo: 'github-actions-testing',
              status: 'failure',
              page: 1,
              per_page: 100
            })
            
            for(let i=0; i < runs.data.workflow_runs.length; i++) {
              const run_id = runs.data.workflow_runs[i].id
              const run_name = runs.data.workflow_runs[i].name
              const workflow_id = runs.data.workflow_runs[i].workflow_id
              const created_at = runs.data.workflow_runs[i].created_at
              const updated_at = runs.data.workflow_runs[i].created_at
              const actor = runs.data.workflow_runs[i].triggering_actor.login
              const head_commit_id = runs.data.workflow_runs[i].head_commit.id
              
              console.log(i+1 + "\trun_id: " + run_id)
              console.log("\trun_name: " + run_name)
              console.log("\tworkflow_id: " + workflow_id)
              console.log("\tcreated_at: " + created_at)
              console.log("\tupdated_at: " + updated_at)
              console.log("\tactor: " + actor)
              console.log("\thead_commit_id: " + head_commit_id)
            }
            
            let fs = require('fs')
            fs.writeFile("list_failure_runs.json", JSON.stringify(runs.data.workflow_runs), function(err) {
              if (err) {
                console.log(err)
              }
            })

      - name: Delete Failure Runs
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.CLOUD_PLATFORM_BOT_PAT }}
          script: |
            const list_failure_runs = require('./list_failure_runs.json')
            
            for(let i=0; i < list_failure_runs.length; i++) {
              const run_id = runs.data.workflow_runs[i].id
              const run_name = runs.data.workflow_runs[i].name
              const workflow_id = runs.data.workflow_runs[i].workflow_id
              
              const delete_runs = await github.rest.actions.deleteWorkflowRun({
                owner: 'sonadztux',
                repo: 'github-actions-testing',
                run_id: run_id
              })
              console.log("Workflow run '"+ run_name + "' run id: " + run_id + " on workflow id: " + workflow_id + " successfully deleted.")
            }
