name: Delete Workflow Runs
on:
  workflow_dispatch:
    inputs:
      workflowId: 
        description: "Workflow ID"
        required: true

jobs:
  delete_runs:
    name: Delete Runs In Workflow ID ${{github.event.inputs.workflowId}}
    runs-on: ubuntu-latest

    steps:
      - name: Get Workflow Information
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.SONADZTUX_GITHUB_ACTIONS_PAT }}
          script: |
            const workflowInfo = await github.rest.actions.getWorkflow({
              owner: 'sonadztux',
              repo: 'github-actions-testing',
              workflow_id: ${{github.event.inputs.workflowId}},
              page: 1,
              per_page: 100
            })
            console.log(workflowInfo.data)
            
      - name: List Workflow Runs
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.SONADZTUX_GITHUB_ACTIONS_PAT }}
          script: |
            const workflowRuns = await github.rest.actions.listWorkflowRuns({
              owner: 'sonadztux',
              repo: 'github-actions-testing',
              workflow_id: ${{github.event.inputs.workflowId}},
              page: 1,
              per_page: 100
            })
            
            for(let i=0; i < workflowRuns.data.workflow_runs.length; i++) {
              const runId = workflowRuns.data.workflow_runs[i].id
              const runName = workflowRuns.data.workflow_runs[i].name
              const workflowId = workflowRuns.data.workflow_runs[i].workflow_id
              const createdAt = workflowRuns.data.workflow_runs[i].created_at
              const updatedAt = workflowRuns.data.workflow_runs[i].created_at
              const actor = workflowRuns.data.workflow_runs[i].triggering_actor.login
              const headCommitId = workflowRuns.data.workflow_runs[i].head_commit.id
              
              console.log(i+1 + ". run_id: " + runId)
              console.log("   run_name: " + runName)
              console.log("   workflow_id: " + workflowId)
              console.log("   created_at: " + createdAt)
              console.log("   updated_at: " + updatedAt)
              console.log("   actor: " + actor)
              console.log("   head_commit_id: " + headCommitId)
            }

            let fs = require('fs')
            fs.writeFile("list_workflow_runs.json", JSON.stringify(workflowRuns.data.workflow_runs), function(err) {
              if (err) {
                console.log(err)
              }
            })

      - name: Delete Workflow Runs
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.SONADZTUX_GITHUB_ACTIONS_PAT }}
          script: |
            const list_workflow_runs = require('./list_workflow_runs.json')
            
            for(let i=0; i < list_workflow_runs.length; i++) {
              const runId = list_workflow_runs[i].id
              const runName = list_workflow_runs[i].name
              const workflowId = list_workflow_runs[i].workflow_id
              
              console.log("- Start deleting workflow run '"+ runName + "' run id: " + runId + " on workflow id: " + workflowId)
              const delete_runs = await github.rest.actions.deleteWorkflowRun({
                owner: 'sonadztux',
                repo: 'github-actions-testing',
                run_id: runId
              })
              console.log("  Workflow runs log successfully deleted.")
            }
